### ISSUE TITLE
TypeError: Cannot call a class as a function

### ISSUE THREAD

**Issue by ahelord** [leebenson/graphql-with-sequelize#9]
hello I found this error when I run
./node_modules/.bin/babel-node server.js
here all the trace of information:

`/Users/lrodriguez/graphql-sequelize-test/graphql-with-sequelize/node_modules/graphql/node_modules/babel-runtime/helpers/class-call-check.js:5
    throw new TypeError("Cannot call a class as a function");
   TypeError: Cannot call a class as a function
    at exports.default (/Users/lrodriguez/graphql-sequelize-test/graphql-with-sequelize/node_modules/graphql/node_modules/babel-runtime/helpers/class-call-check.js:5:11)
    at GraphQLNonNull (/Users/lrodriguez/graphql-sequelize-test/graphql-with-sequelize/node_modules/graphql/type/definition.js:759:5)
    at fields (/Users/lrodriguez/graphql-sequelize-test/graphql-with-sequelize/schema.js:137:19)
    at resolveMaybeThunk (/Users/lrodriguez/graphql-sequelize-test/graphql-with-sequelize/node_modules/graphql/type/definition.js:265:47)
    at defineFieldMap (/Users/lrodriguez/graphql-sequelize-test/graphql-with-sequelize/node_modules/graphql/type/definition.js:284:18)
    at GraphQLObjectType.getFields (/Users/lrodriguez/graphql-sequelize-test/graphql-with-sequelize/node_modules/graphql/type/definition.js:245:46)
    at /Users/lrodriguez/graphql-sequelize-test/graphql-with-sequelize/node_modules/graphql/type/schema.js:174:29
    at typeMapReducer (/Users/lrodriguez/graphql-sequelize-test/graphql-with-sequelize/node_modules/graphql/type/schema.js:186:9)
    at Array.reduce (native)
    at new GraphQLSchema (/Users/lrodriguez/graphql-sequelize-test/graphql-with-sequelize/node_modules/graphql/type/schema.js:81:120)
    at Object.<anonymous> (/Users/lrodriguez/graphql-sequelize-test/graphql-with-sequelize/schema.js:159:16)
    at Module._compile (module.js:570:32)
    at loader (/Users/lrodriguez/graphql-sequelize-test/graphql-with-sequelize/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/lrodriguez/graphql-sequelize-test/graphql-with-sequelize/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)`

**Comment by leebenson** [comment]
This is quite an old repo now. You're probably using a later version of Babel that this hasn't been tested with. I'd accept a PR with a fix.

**Comment by aapav01** [comment]
u need to add "new" at line 137, 140 and 143 in schema.js

addPost: {
        type: Post,
        args: {
          userId: {
            type: new GraphQLNonNull(GraphQLInt)
          },
          title: {
            type: new GraphQLNonNull(GraphQLString)
          },
          content: {
            type: new GraphQLNonNull(GraphQLString)
          }
        },

**Comment by leebenson** [comment]
This is a very old example and probably mostly redundant.

I’d recommend anyone reading instead use a newer lib such as Apollo v2.
